version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
